Repository amundsen-io/rfcs, pull requests merged in 2021-03, with the labels that each got.

#20 Automated Release Process
  rfcs/020-automated-release-process.md
Labels: Status: Final Comment Period (FCP)

#12 Proposes the use of Python's Dataclasses
  rfcs/000-python-dataclasses.md
Labels: Status: Active

#25 Lineage Stage 0
  assets/025/column-lineage-preview.png
  assets/025/lineage-arch.png
  assets/025/table-lineage-preview.png
  rfcs/025-lineage-stage-0.md
Labels: Status: Landed

#23 Add MySQL as a data sink in the databuilder
  rfcs/000-support-mysql-as-backend-store.md
Labels: Status: Landed

#17 Migrate to Official Python Atlas Client
  rfcs/000-migration-official-atlas-client.md
Labels: Status: Active

#29 Table and Dashboard Notices
  rfcs/012-python-dataclasses.md
  rfcs/019-support-rdb-models.md
  rfcs/021-abstract-serializable-for-relational-db.md
  rfcs/023-support-mysql-as-backend-store.md
  rfcs/029-resource-notices.md
Labels: Status: Active
